
platform:
- x64

image: Visual Studio 2019

environment:
  matrix:    
    - PYTHON_VERSION: 39-x64
      ARCH: x64
      
build: off

before_build:
    - appveyor DownloadFile https://github.com/Pusnow/mecab-ko-msvc/releases/download/release-0.9.2-msvc-3/mecab-ko-msvc-%ARCH%.zip
    - 7z x mecab-ko-msvc-%ARCH%.zip -oc:\mecab
    - C:\Python%PYTHON_VERSION%\python.exe -m pip install wheel
    - C:\Python%PYTHON_VERSION%\python.exe -m pip install -U setuptools
    
build_script:
    - build.cmd C:\Python%PYTHON_VERSION%\python.exe setup.py bdist_wheel
    

artifacts: 
  - path: 'dist\*.whl'
    name: MeCab-Python-MSVC
deploy:
  description: 'MeCab-Python-MSVC'
  provider: GitHub
  auth_token:
    secure: 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
  artifact: MeCab-Python-MSVC    
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
